# Generated by Django 3.0.8 on 2021-03-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='session_end',
            new_name='session_token',
        ),
    ]
